% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 05-Oct-2017 19:06:32
%
% This script assumes these variables are defined:
%
%   simpleclusterInputs - input data.

x = simpleclusterInputs;

% Create a Self-Organizing Map
dimension1 = 4;
dimension2 = 4;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,x);

% Test the Network
y = net(x);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

